import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { AITaskConfigService } from '../chat/ai-task-config.service';
import { AuthService } from '@gitroom/helpers/auth/auth.service';
import { validateBaseUrlOrDefault } from './url-validator';
import pLimit from 'p-limit';

const limit = pLimit(10);

/**
 * Decrypted FAL provider for internal use
 * Contains sensitive information that should never be sent to the client
 */
interface DecryptedFALProvider {
  id: string;
  name: string;
  type: string;
  apiKey: string; // decrypted
  baseUrl?: string;
  enabled: boolean;
}

/**
 * FAL.ai Service
 * Provides image generation via FAL API (Ideogram, FLUX, Stable Diffusion, etc.)
 * Supports organization-specific provider configuration with fallback to environment variable
 */
@Injectable()
export class FalService {
  private readonly logger = new Logger(FalService.name);

  constructor(
    private readonly aiTaskConfig: AITaskConfigService
  ) {}

  /**
   * Get the configured FAL provider for an organization
   * Falls back to environment variable if no database provider is configured
   * @param organizationId - Organization ID for provider lookup
   * @returns Decrypted provider configuration or null
   */
  private async getProvider(organizationId?: string): Promise<DecryptedFALProvider | null> {
    // Try database-configured provider first
    if (organizationId) {
      try {
        const provider = await this.aiTaskConfig.getTaskProvider('image', organizationId);

        // Check if it's a FAL provider
        if (provider && provider.type === 'fal' && provider.enabled) {
          const decryptedKey = AuthService.fixedDecryption(provider.apiKey);
          return {
            id: provider.id,
            name: provider.name,
            type: provider.type,
            apiKey: decryptedKey,
            baseUrl: provider.baseUrl || undefined,
            enabled: provider.enabled,
          };
        }
      } catch (error) {
        this.logger.warn(`FAL provider lookup failed for org ${organizationId}, falling back to env var`);
      }
    }

    // Fall back to environment variable (global configuration)
    const envKey = process.env.FAL_KEY;
    if (envKey) {
      return {
        id: 'env-fallback',
        name: 'FAL (Environment)',
        type: 'fal',
        apiKey: envKey,
        baseUrl: process.env.FAL_BASE_URL || 'https://fal.run',
        enabled: true,
      };
    }

    return null;
  }

  /**
   * Generate an image from text using FAL API
   * @param model - FAL model identifier (e.g., 'ideogram/v2', 'fast-sdxl')
   * @param text - Prompt for image generation
   * @param isVertical - Whether to generate vertical (9:16) or horizontal (16:9) image
   * @param organizationId - Organization ID for provider configuration lookup
   * @returns URL of the generated image
   * @throws NotFoundException if no FAL provider is configured
   */
  async generateImageFromText(
    model: string,
    text: string,
    isVertical: boolean = false,
    organizationId?: string
  ): Promise<string> {
    const provider = await this.getProvider(organizationId);

    if (!provider) {
      throw new NotFoundException(
        'No FAL provider configured. Please add a FAL provider in the AI providers settings or set FAL_KEY environment variable.'
      );
    }

    const baseUrl = validateBaseUrlOrDefault(provider.baseUrl, 'https://fal.run');
    const apiUrl = `${baseUrl}/fal-ai/${model}`;

    try {
      const response = await limit(() =>
        fetch(apiUrl, {
          method: 'POST',
          headers: {
            Authorization: `Key ${provider.apiKey}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            prompt: text,
            aspect_ratio: isVertical ? '9:16' : '16:9',
            resolution: '720p',
            num_images: 1,
            output_format: 'jpeg',
            expand_prompt: true,
          }),
        })
      );

      // Validate response before processing
      if (!response.ok) {
        const errorText = await response.text().catch(() => 'Unknown error');
        throw new Error(`FAL API error: ${response.status} ${response.statusText} - ${errorText}`);
      }

      const { images, video, ...all } = await response.json();

      this.logger.debug(`FAL response: ${JSON.stringify({ hasImage: !!images, hasVideo: !!video })}`);

      if (video) {
        return video.url;
      }

      if (!images || images.length === 0) {
        throw new Error('No image generated by FAL API');
      }

      return images[0].url as string;
    } catch (error) {
      this.logger.error(`FAL API error: ${error instanceof Error ? error.message : String(error)}`);
      throw error;
    }
  }
}
